title: Hosty
description: Ad blocker script for all Unix and Unix-like operating systems (Linux, GNU, BSD, Mac OS X, FreeBSD, OpenBSD).
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
